---
  
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
    dockerImageRepository: quay.io/naps_healthcare/patient_service
